[tool.black]
line-length = 120
target-version = ["py310"]

[tool.ruff]
line-length =120
target-version = "py310"
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM"]

[tool.ruff.lint.isort]
known-first-party = ["agent"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
no_implicit_optional = true
